---

- name: Creates the jump host Droplet
  digital_ocean_droplet:
    state: present
    name: "{{ jumphost.name }}"
    unique_name: "{{ jumphost.unique_name }}"
    image: "{{ jumphost.image }}"
    size: "{{ jumphost.size }}"
    region: "{{ jumphost.region }}"
    monitoring: "{{ jumphost.monitoring }}"
    private_networking: "{{ jumphost.private_networking }}"
    ssh_keys: "{{ jumphost.ssh_keys }}"
    oauth_token: "{{ jumphost.oauth_token }}"
  register: jumphost_droplet

- name: Show the jump host's IP information
  debug:
    msg: |
      ssh root@{{ jumphost_droplet.data.ip_address }}
      ssh root@{{ jumphost_droplet.data.private_ipv4_address }}
